# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = [
    {
        :name => "psql-master",
        :type => "master",
        :box => "hashicorp/bionic64",
        :box_version => "1.0.282",
        :eth1 => "192.168.10.115",
        :mem => "2048",
        :cpu => "2"
    },
    {
        :name => "psql-slave",
        :type => "slave",
        :box => "hashicorp/bionic64",
        :box_version => "1.0.282",
        :eth1 => "192.168.10.116",
        :mem => "2048",
        :cpu => "2"
    }
]

Vagrant.configure("2") do |config|

    servers.each do |opts|
        config.vm.define opts[:name] do |config|

            config.vm.box = opts[:box]
            config.vm.box_version = opts[:box_version]
            config.vm.hostname = opts[:name]
            config.vm.network :private_network, ip: opts[:eth1]

            config.vm.provider "virtualbox" do |v|

                v.name = opts[:name]
            	v.customize ["modifyvm", :id, "--groups", "/PostgreSQL DevOps Team"]
                v.customize ["modifyvm", :id, "--memory", opts[:mem]]
                v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]

            end

            config.vm.provision "shell", path: "./postgresql/bootstrap.sh"

            if opts[:type] == "master"
               config.vm.provision "shell", path: "./postgresql/master-conf.sh"
               config.vm.provision "file", source: "./test/pgtest-master.sh", destination: "/home/vagrant/test/pgtest-master.sh"

            else
               config.vm.provision "shell", path: "./postgresql/slave-conf.sh"
               config.vm.provision "file", source: "./test/pgtest-slave.sh", destination: "/home/vagrant/test/pgtest-slave.sh"
               config.vm.provision "shell", path: "./postgresql/replica-conf.sh"
            end

        end

    end

end