# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = [
    {
        :name => "jmeter-vm",
        :box => "hashicorp/bionic64",
        :box_version => "1.0.282",
        :eth1 => "192.168.10.120",
        :mem => "2048",
        :cpu => "2"
    }
]

Vagrant.configure("2") do |config|

    servers.each do |opts|
        config.vm.define opts[:name] do |config|

            config.vm.box = opts[:box]
            config.vm.box_version = opts[:box_version]
            config.vm.hostname = opts[:name]
            config.vm.network :private_network, ip: opts[:eth1]

            config.vm.provider "virtualbox" do |v|

                v.name = opts[:name]
            	v.customize ["modifyvm", :id, "--groups", "/JMeter DevOps Team"]
                v.customize ["modifyvm", :id, "--memory", opts[:mem]]
                v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]

            end

            config.vm.provision "shell", path: "bootstrap.sh"
            config.vm.provision "file", source: "jmeter.sh", destination: "/home/vagrant/jmeter/jmeter.sh"
            config.vm.provision "file", source: "./test/jmx/Postgresql.jmx", destination: "/home/vagrant/jmeter/test/jmx/Postgresql.jmx"

        end

    end

end