# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = [
    {
        :name => "k8s-master",
        :type => "master",
        :box => "hashicorp/bionic64",
        :box_version => "1.0.282",
        :eth1 => "192.168.10.10",
        :mem => "2048",
        :cpu => "2"
    },
    {
        :name => "k8s-node-1",
        :type => "node",
        :box => "hashicorp/bionic64",
        :box_version => "1.0.282",
        :eth1 => "192.168.10.11",
        :mem => "6144",
        :cpu => "4"
    },
    {
        :name => "k8s-node-2",
        :type => "node",
        :box => "hashicorp/bionic64",
        :box_version => "1.0.282",
        :eth1 => "192.168.10.12",
        :mem => "6144",
        :cpu => "4"
    }
]

Vagrant.configure("2") do |config|

    servers.each do |opts|
        config.vm.define opts[:name] do |config|

            config.vm.box = opts[:box]
            config.vm.box_version = opts[:box_version]
            config.vm.hostname = opts[:name]
            config.vm.network :private_network, ip: opts[:eth1]

            config.vm.provider "virtualbox" do |v|

                v.name = opts[:name]
            	v.customize ["modifyvm", :id, "--groups", "/Kubernetes DevOps Team"]
                v.customize ["modifyvm", :id, "--memory", opts[:mem]]
                v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]

            end

            config.vm.provision "shell", path: "./kubernetes/bootstrap.sh"

            if opts[:type] == "master"
                config.vm.provision "shell", path: "./kubernetes/master-conf.sh"
                config.vm.provision "file", source: "./kubernetes-dashboard/dashboard.sh", destination: "/home/vagrant/dashboard.sh"
                config.vm.provision "file", source: "../helm/helm-bootstrap.sh", destination: "/home/vagrant/helm-bootstrap.sh"
                config.vm.provision "file", source: "../helm/gitlab/deploy-gitlab.sh", destination: "/home/vagrant/deploy-gitlab.sh"
                config.vm.provision "file", source: "../helm/gitlab/PersistentVolume.yaml", destination: "/home/vagrant/PersistentVolume.yaml"
                config.vm.provision "file", source: "./kubernetes-dashboard/dashboard.sh", destination: "/home/vagrant/dashboard.sh"
            else
                config.vm.provision "shell", path: "./kubernetes/node-conf.sh"
            end
            if opts[:name] == "k8s-node-2"
                config.vm.provision "shell", path: "./kubernetes/deployment.sh"
            end
        end
    end
end