---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-minio-volume
  labels:
    type: local
spec:
  storageClassName: gitlab-minio-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-postgresql-volume
  labels:
    type: local
spec:
  storageClassName: gitlab-postgresql-storage
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-prometheus-volume
  labels:
    type: local
spec:
  storageClassName: gitlab-prometheus-storage
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-redis-volume
  labels:
    type: local
spec:
  storageClassName: gitlab-redis-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-gitaly-volume
  labels:
    type: local
spec:
  storageClassName: gitlab-redis-storage
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
